services:
  postgres:
    image: postgres:15.2
    ports:
      - 5432:5432
    volumes:
      - accounting-postgres:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  accounting-postgres:
    external: true
