name: 'Tests'
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      # https://pnpm.io/continuous-integration#github-actions
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install rclone
        run: sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Add rclone.conf
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf
          rclone -vv copy r2:accounting/ web/src/documents/

      - name: Add .env
        run: echo '${{ secrets.WEB_ENV }}' > web/.env

      - name: Run tests
        run: |
          pnpm test
          pnpm exec playwright install --with-deps
          pnpm run test-e2e
        working-directory: web
