name: 'Tests'
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      # https://pnpm.io/continuous-integration#github-actions
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install rclone
        run: sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Add rclone.conf
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf
          rclone -vv copy r2:accounting/ web/src/documents/

      - name: Add .env
        run: echo '${{ secrets.WEB_ENV }}' > web/.env

      - run: pnpm test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - run: pnpm run test-e2e
