name: 'Tests'
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v4

      # https://pnpm.io/continuous-integration#github-actions
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install rclone
        run: sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Add rclone.conf
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf
          rclone -vv copy r2:accounting/ tests/documents/

      - name: Add .env
        run: echo '${{ secrets.WEB_ENV }}' > .env

      - run: pnpm test

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - run: pnpm run test-e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tests-report
          path: ./tests/report
          retention-days: 30
