name: accounting
services:
  postgres:
    image: postgres:15.2
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - accounting-postgres:/var/lib/postgresql/data

volumes:
  accounting-postgres:
    external: true
